#!/bin/bash
YEAR=2022
DAY=${1}

# grab this once via dev tools from any request after you've logged into AoC
COOKIE=<auth cookie goes here>

cp -R tmpl "day${DAY}"
pushd "day${DAY}"

curl -s --cookie "session=${COOKIE}" https://adventofcode.com/${YEAR}/day/${DAY}/input > input

# probably a Mac-ism, apols to anyone else
open -a 'Google Chrome' https://adventofcode.com/${YEAR}/day/${DAY}

# change to $IDE_OF_CHOICE
code .
popd
